import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-hidden bg-slate-200 h-screen w-screen `}
      >
        <div className="flex flex-col w-full h-full">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
